# Catppuccin Latte
# https://github.com/catppuccin/catppuccin

[colors]
foreground           = "#4c4f69"
background           = "#eff1f5"
cursor               = "#dc8a78"
cursor_text          = "#eff1f5"
selection_background = "#acb0be"
selection_foreground = "#4c4f69"

[palette]
0  = "#5c5f77"
1  = "#d20f39"
2  = "#40a02b"
3  = "#df8e1d"
4  = "#1e66f5"
5  = "#ea76cb"
6  = "#179299"
7  = "#acb0be"
8  = "#6c6f85"
9  = "#d20f39"
10 = "#40a02b"
11 = "#df8e1d"
12 = "#1e66f5"
13 = "#ea76cb"
14 = "#179299"
15 = "#bcc0cc"
