# Dracula
# https://draculatheme.com

[colors]
foreground           = "#f8f8f2"
background           = "#282a36"
cursor               = "#f8f8f2"
cursor_text          = "#282a36"
selection_background = "#44475a"
selection_foreground = "#f8f8f2"

[palette]
0  = "#21222c"
1  = "#ff5555"
2  = "#50fa7b"
3  = "#f1fa8c"
4  = "#bd93f9"
5  = "#ff79c6"
6  = "#8be9fd"
7  = "#f8f8f2"
8  = "#6272a4"
9  = "#ff6e6e"
10 = "#69ff94"
11 = "#ffffa5"
12 = "#d6acff"
13 = "#ff92df"
14 = "#a4ffff"
15 = "#ffffff"
